Error correction
D:\Windows11\destkop\LiveAtlas-master\.pnp.cjs:15329
  return Object.defineProperties(new Error(message), {
                                 ^

Error: Required unplugged package missing from disk. This may happen when switching branches without running installs (unplugged packages must be fully materialized on disk to work).

Missing package: esbuild@npm:0.18.11
Expected package location: D:\Windows11\destkop\LiveAtlas-master\.yarn\unplugged\esbuild-npm-0.18.11-7ebdd30a31\node_modules\esbuild\

    at makeError (D:\Windows11\destkop\LiveAtlas-master\.pnp.cjs:15329:34)
    at resolveUnqualified (D:\Windows11\destkop\LiveAtlas-master\.pnp.cjs:17090:17)
    at resolveRequest (D:\Windows11\destkop\LiveAtlas-master\.pnp.cjs:17142:14)
    at Object.resolveRequest (D:\Windows11\destkop\LiveAtlas-master\.pnp.cjs:17198:26)
    at resolve$1 (file:///D:/Windows11/destkop/LiveAtlas-master/.pnp.loader.mjs:1989:21)
    at async nextResolve (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.resolve (node:internal/modules/esm/loader:835:24)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:7)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:21)

Node.js v18.17.0

[vite]: Rollup failed to resolve import "leaflet/dist/leaflet.css" from "D:/Windows11/destkop/LiveAtlas-master/src/main.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`